apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: ecommerce
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
