apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: ecommerce
spec:
  selector:
    app: cart
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
