apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: ecommerce
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
